version: 0.2

env:
  variables:
    FRAMEWORK_VERSION: "1.3.0"
    PREPROD_IMAGE: "142577830533.dkr.ecr.us-west-2.amazonaws.com/sagemaker-framework-pull-request-integ"
    CPU_FRAMEWORK_BINARY: "https://files.pythonhosted.org/packages/71/64/49c5125befd5e0f0e17f115d55cb78080adacbead9d19f253afd0157656a/mxnet-1.3.0.post0-py2.py3-none-manylinux1_x86_64.whl"
    CPU_PY_VERSION: "py2"
    CPU_TAG: "$FRAMEWORK_VERSION-cpu-$CPU_PY_VERSION-$CODEBUILD_BUILD_ID"
    CPU_INTEGRATION_TEST_COMMAND: "pytest test/integration/local --docker-base-name $PREPROD_IMAGE --tag $CPU_TAG --framework-version $FRAMEWORK_VERSION --py-version $CPU_PY_VERSION --processor cpu"


phases:
  pre_build:
    commands:
      # create and activate conda env
      - conda create -y -n py36 python=3.6
      - source activate py36

      # run unit tests
      - pip install -U .[test]
      - pytest test/unit


  build:
    commands:
      # build cpu image
      - |
        build_dir="docker/$FRAMEWORK_VERSION/final"
        cpu_dockerfile="Dockerfile.cpu"

        # Download framework binary
        cpu_fw_binary=$(basename $CPU_FRAMEWORK_BINARY)
        wget -O $build_dir/$cpu_fw_binary $CPU_FRAMEWORK_BINARY

        # Create tensorflow-container pip archive
        python setup.py sdist
        # tar_name will be something like: sagemaker_mxnet_container-1.0.tar.gz
        tar_name=$(ls dist)
        cp dist/$tar_name $build_dir

        cd $build_dir
        docker build -f $cpu_dockerfile --build-arg py_version=$CPU_PY_VERSION --build-arg framework_installable=$cpu_fw_binary -t $PREPROD_IMAGE:$CPU_TAG .
        cd ../../../

      # run integration tests
      - |
        TEST_REQUIRED_CHANGES=("test/" "tests/" "src/*.py" "docker/*")
        INTEG_TEST_REQUIRED=false

        # diff between master and the pr branch excluding merges.
        CHANGED_FILES=$(git log origin/master..HEAD --oneline --no-merges --name-only --pretty=format:"%H")

        for i in ${TEST_REQUIRED_CHANGES[@]}; do
            if [[ $CHANGED_FILES = *$i* ]]
            then
                echo "Change detected in "$i
                INTEG_TEST_REQUIRED=true
                break
            fi
        done

        echo "Run integration tests:" $INTEG_TEST_REQUIRED

        if [ $INTEG_TEST_REQUIRED = true ]
        then
            echo "Running integration tests"
            eval $CPU_INTEGRATION_TEST_COMMAND
        fi
